### ISSUE TITLE
Fading effect is not there when minimized view is dragged in horizontal direction

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [pedrovgs/DraggablePanel#18]
I am using draggable panel library in my project .  Just like youtube app fades to transparent halfway when move to left or right(when vedio is minimized) . In this demo sample app it is not showing such behavior though i can find code is there for handling setEnablealpha() . 
So how to solve this issue

**Comment by pedrovgs** [comment]
As Fiddl3 says, you can use setHorizontalAlphaEffectEnabled method to enable/disable this visual effect or use xml customization based on attrs. This library is going to apply that effect but some views are not going to support it, this is an Android bug and not a bug related with this library.

**Comment by Fiddl3** [comment]
I deleted my prev answer by mistake....

by default this is enabled, but you can

In java you can enable/disable apha effect:
draggablePanel.setEnableHorizontalAlphaEffect(true|false);
or
draggableView.setHorizontalAlphaEffectEnabled(true|false);

in XML:
draggable_view:enable_horizontal_alpha_effect="true|false"

fading of dragView is controlled by method changeDragViewViewAlpha() in draggableView

This will not work with Views that uses SurfaceView to display content (ex: video) because default PixelFormat of holder doesn't support alpha channel or support only one bit (visible/invisible)
There are 2 solutions:
1) Change PixelFormat to one that support alphatransparency - http://developer.android.com/reference/android/graphics/PixelFormat.html#TRANSLUCENT
2) Put View in container, set background of container, set visibility of View to INVISIBLE while moving

I suppose YT player use SyfraceView too, but I'm not sure
